version: "3.1"
services:
  frontend:
    build: frontend
    ports:
      - 8080:8080
    links:
    - "backend:backend"
  
  backend:
    build: backend
    ports:
      - 8081:8081
    links:
      - "mongo:database"
    environment:
      MONGO_URI: "http://database"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example


    
    
